Virtual Store/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Virtual_Store.Models;

namespace Virtual_Store.Controllers
{
    public class HomeController : Controller
    {
        private VirtualStoreDBEntities db = new VirtualStoreDBEntities();
        public ActionResult Index()
        {

            var products = db.Products;

            ViewBag.Products = products.Where(p => p.price > 100 && p.stock>5)
                .OrderBy(p=>p.price)
                .Take(5)
                .ToList();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Virtual Store.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Más información en.";
            ViewBag.GitRepo = "https://gitlab.com/daxamayac/virtual-store.git";
            return View();
        }
    }
}

Virtual Store/Controllers/ShoppingController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Virtual_Store.Models;

namespace Virtual_Store.Controllers
{
    public class ShoppingController : Controller
    {
        private VirtualStoreDBEntities db = new VirtualStoreDBEntities();
        private double total = 0;

        // GET: Shopping
        public ActionResult Index()
        {
            ViewBag.categories = db.Categories.ToList();
            ViewBag.products = db.Products.ToList();
            return View();
        }


        public ActionResult Category(int id)
        {
            var categories = db.Categories.ToList();
            var categoryEnable = db.Categories.Find(id);
            var products = categoryEnable.Products;
            ViewBag.categoryEnable = categoryEnable.name;
            ViewBag.categories = categories;
            ViewBag.products = products;

            return View("Index");
        }


        public ActionResult Add(int id, ShoppingCart sc)
        {
            Product prod = db.Products.Find(id);

            ProductItem pi = new ProductItem();
            pi.Id = prod.Id;
            pi.image = prod.image;
            pi.name = prod.name;
            pi.quantity = 1;
            pi.price = prod.price;

            if (sc.Find(item => item.Id == pi.Id) != null) {
                sc.Find(item => item.Id == pi.Id).quantity += 1;
            }
            else
                sc.Add(pi);


            ViewBag.total = sc.Sum(item => item.price * item.quantity);

            return View("Cart", sc);
        }

        public ActionResult Remove(int id, ShoppingCart sc)
        {

            if (sc.Find(item => item.Id == id) != null)
            {
                sc.Remove(sc.Find(item => item.Id == id));
            }

            ViewBag.total = sc.Sum(item => item.price * item.quantity);

            return View("Cart", sc);
        }

        public ActionResult Cart(ShoppingCart sc)
        {
            ViewBag.total = sc.Sum(item => item.price * item.quantity);

            return View("Cart", sc);
        }

        [Authorize]
        public ActionResult Payment(ShoppingCart sc)
        {
            ViewBag.total = sc.Sum(item => item.price * item.quantity);
            ViewBag.cart = sc;

            return View("Payment");
        }
        [Authorize]
        public ActionResult Pay(ShoppingCart sc)
        {

            Order o = new Order();

            o.date = DateTime.UtcNow;
            o.referenceUser = User.Identity.Name;
            o.status = "Enviado";
            o.shippingAddress = "Direccion de envio comprador";
            o.name = User.Identity.Name;
            db.Orders.Add(o);
            db.SaveChanges();

            double total = 0;

            foreach (ProductItem pi in sc.ToList()) {

                OrderDetail od = new OrderDetail();
                Product p = db.Products.Find(pi.Id);
                od.quantity = pi.quantity;
                od.Product = p;
                od.price = pi.price;
                od.Order = o;
                db.OrderDetails.Add(od);

                
                p.stock = p.stock - pi.quantity;
                total += pi.quantity * pi.price;

                db.SaveChanges();
            }

            o.total = total;
            db.SaveChanges();

            Session.Clear();

            ViewBag.orders = db.Orders.Where(user => user.referenceUser == User.Identity.Name).OrderByDescending(or => or.date).ToList();

            return View("Orders");
        }
        [Authorize]
        public ActionResult Orders()
        {
            ViewBag.orders = db.Orders.Where(user => user.referenceUser == User.Identity.Name).OrderByDescending(or => or.date).ToList();

            return View("Orders");
        }
    }
}

Virtual Store/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<h3>Tecnologías utilizadas</h3>
<ul>
    <li>.NET Framework</li>
    <li>MySql (Store File)</li>
    <li>Bootstrap</li>
</ul>

<h3>Features</h3>
que hace la app
<ul>
    <li></li>
    
</ul>

Virtual Store/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Store";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<h3>Git repository</h3>
<h4>@ViewBag.GitRepo</h4>

<br/>
<address>
    UPM student<br />
    Máster en Ingeniería Web - .NET<br />
    <!-- <abbr title="Phone">P:</abbr>
     425.555.0100-->
</address>

<address>
    <strong>Personal:</strong>   <a href="mailto:daxamayac@gmail.com">daxamayac@gmail.com</a><br />
    <strong>Student:</strong> <a href="mailto:d.acruz@alumnos.upm.es">d.acruz@alumnos.upm.es</a>
</address>

Virtual Store/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@using Virtual_Store.Models

<div class="jumbotron" style="
      background-image: url('/Content/home.jpg');
      background-position: center;
      background-size:cover;
      min-height: 50vh;
    ">
    <h1>VIX STORE</h1>
    <p class="lead">Tienda virtual de ropa, accesorios y material para todo varios deportes</p>
    <p>
        <a href="@Url.Action("Index","Shopping")" class="btn btn-primary btn-lg">Tienda &raquo;</a>
    </p>
</div>


<div class="row">
    <div class="col-md-4">
        <h2>Escoge</h2>
        <p>
            Recuerda que para agregar artículos al carrito no hace falta autenticarse.
        </p>

    </div>
    <div class="col-md-4">
        <h2>Pide</h2>
        <p>Para realizar el pago y pedido es necesario que tengas una cuenta y estes autenticado en la tienda.</p>

    </div>
    <div class="col-md-4">
        <h2>Espera</h2>
        <p>Una vez realizado el pedido, será entregado en un máximo de 48 horas.</p>
    </div>

</div>

<div class="jumbotron">
    
        <div class="  alert alert-dark" role="alert">
            <h3>Los mejores productos!!!</h3>
        </div>
        <div class="row">


            @foreach (Product p in ViewBag.Products)
            {
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <!-- <a href="#"><img class="card-img-top" src="@p.image" alt=""></a>-->
                        <img class="card-img-top" src="@p.image" alt="">
                        <div class="card-body">
                            <h4 class="card-title">
                                <!-- <a href="#">@p.name</a>-->
                                @p.name
                            </h4>
                            <h5>$@p.price</h5>
                            <p class="card-text">@p.description</p>
                        </div>
                        <div class="card-footer">
                            <a href="#">
                                @Html.ActionLink("Añade al Carrito", "Add", "Shopping", new { id = p.Id }, null)
                            </a>
                        </div>
                    </div>

                </div>

            }

        </div>

    <p>
        <a href="@Url.Action("Index","Shopping")" class="btn btn-primary btn-lg">Ver más productos &raquo;</a>
    </p>
</div>